services:
  back:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    networks:
      - mgn-network

  front:
    build:
      context: ./src/front
      dockerfile: Dockerfile
      args:
        - PUBLIC_API_URL=http://localhost:3000  
        - PUBLIC_AUTH0_DOMAIN_MGN=${PUBLIC_AUTH0_DOMAIN_MGN}
        - PUBLIC_AUTH0_CLIENT_ID_MGN=${PUBLIC_AUTH0_CLIENT_ID_MGN}
    ports:
      - "8080:80"
    depends_on:
      - back
    networks:
      - mgn-network

networks:
  mgn-network:
    driver: bridge